<?php

namespace App\Filament\Resources\Risk\RiskResource\Pages;

use App\Filament\Resources\Risk\RiskResource;
use Filament\Forms\Components\Fieldset;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Filament\Tables\Filters\Layout;
use Illuminate\Database\Eloquent\Builder;

class ListRisks extends ListRecords
{
    protected static string $resource = RiskResource::class;

    protected function getActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
//    protected function getTableFiltersLayout(): ?string
//    {
//        return Layout::Popover;
//    }

    protected function getTableFiltersFormColumns(): int
    {
        return 2;
    }

    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()
//            ->with('unit', 'territories','departments','positions', 'processes', 'products', 'services')
            ; // TODO: Change the autogenerated stub
    }
}
